# This file was generated by GoReleaser. DO NOT EDIT.
cask "dispositio" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "f3be3a8f44c2b64a3922d7b254b3e6d0b5c97fd90cabebc4901674ca09856af7"
      url "https://github.com/tsraveling/dispositio/releases/download/v#{version}/dispositio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "48e2037897c9378a719a1476825b74697eb4fd4628d4522181b13afec6d07849"
      url "https://github.com/tsraveling/dispositio/releases/download/v#{version}/dispositio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d175811ae7fe6b23b8f7d0ee4724c2173732bf17249d071b50654c93654ba724"
      url "https://github.com/tsraveling/dispositio/releases/download/v#{version}/dispositio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2ae3fb135a356081c4278b22a8c3adc0c5bb3d0490398c3f5a0ff38e75e86b1"
      url "https://github.com/tsraveling/dispositio/releases/download/v#{version}/dispositio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dispositio"
  desc "Terminal tool for planning large projects in simple markdown"
  homepage "https://github.com/tsraveling/dispositio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dispositio"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dispositio"]
    end
  end

  # No zap stanza required

end
