# This file was generated by GoReleaser. DO NOT EDIT.
cask "dispositio" do
  version "0.2.7"

  on_macos do
    on_intel do
      sha256 "060642bd4a9c964b9e8ddf520d3b8e0196ad3ae122bf697e62f1ee7d47a3ec48"
      url "https://github.com/tsraveling/dispositio/releases/download/v#{version}/dispositio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d0dc944b17836446bb6aabbb27cae87a914243ac3331511516af57d93bb025a"
      url "https://github.com/tsraveling/dispositio/releases/download/v#{version}/dispositio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "127563d211d0fb488723eb68a10a676c5480b5e561477ca2cca2d191e9b6019c"
      url "https://github.com/tsraveling/dispositio/releases/download/v#{version}/dispositio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7a0af49ab3d83c8d575886991c438e12f1d56528edb3124c92cc343b608b6e0"
      url "https://github.com/tsraveling/dispositio/releases/download/v#{version}/dispositio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dispositio"
  desc "Terminal tool for planning large projects in simple markdown"
  homepage "https://github.com/tsraveling/dispositio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dispositio"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dispositio"]
    end
  end

  # No zap stanza required

end
