# This file was generated by GoReleaser. DO NOT EDIT.
cask "furnace" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "2b0a6867ae0c56b56f21621ce7454ce4b8573acbad2eeee58f6652b7fc99d42b"
      url "https://github.com/tsraveling/furnace/releases/download/v#{version}/furnace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5fd84a8404ba6d6ef16f5b074701e01cbc3897948830ccc486fa47c5f076efc5"
      url "https://github.com/tsraveling/furnace/releases/download/v#{version}/furnace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "391a8a9c3aacadd27884622f3cd46b626d87af419e1513b87999d680c7219470"
      url "https://github.com/tsraveling/furnace/releases/download/v#{version}/furnace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa057566c5cc21ab5d27e0393e74b173541b1e20864affcb373dc451b64f7c6e"
      url "https://github.com/tsraveling/furnace/releases/download/v#{version}/furnace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "furnace"
  desc "Terminal-based food tracking app"
  homepage "https://github.com/tsraveling/furnace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "furnace"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/furnace"]
    end
  end

  # No zap stanza required

end
