# This file was generated by GoReleaser. DO NOT EDIT.
cask "furnace" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "29851876c50d1832419dd3f178a2dcf5ab1167df7a468e34aa596e2957894d3a"
      url "https://github.com/tsraveling/furnace/releases/download/v#{version}/furnace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "629ef0ed8e626225d1cfaaa79eb83b2f699e15de825e599cd6155eb69761b85b"
      url "https://github.com/tsraveling/furnace/releases/download/v#{version}/furnace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9aadc2d0ae7791d59b60d2249ffe73619e3fbf7d5c5055cbf6c3c70e6b4052fd"
      url "https://github.com/tsraveling/furnace/releases/download/v#{version}/furnace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef7a59668c9a8089a25fbae9caa6e2517db24050fbb67c168f8a3b8c3085d160"
      url "https://github.com/tsraveling/furnace/releases/download/v#{version}/furnace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "furnace"
  desc "Terminal-based food tracking app"
  homepage "https://github.com/tsraveling/furnace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "furnace"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/furnace"]
    end
  end

  # No zap stanza required

end
