# This file was generated by GoReleaser. DO NOT EDIT.
cask "gogo" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "223d0d7a6d9ce4565e5065dae865c9f10aa7bbc800b375265c7ea6502499ed80"
      url "https://github.com/tsraveling/gogo/releases/download/v#{version}/gogo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2bc1a97720dc0d5a238afa6e6a5efcb452b8dadb450ced520fc6ea25e44c0e78"
      url "https://github.com/tsraveling/gogo/releases/download/v#{version}/gogo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "55e34cbb510ec40194795bb4b2f96c5d01091ee977627272e8ade4e7a79f12be"
      url "https://github.com/tsraveling/gogo/releases/download/v#{version}/gogo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ccdccf64a1cb11759e57adfcdd7cf28ff0741c507fc974ad61cea9cbe2fa2ad1"
      url "https://github.com/tsraveling/gogo/releases/download/v#{version}/gogo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gogo"
  desc "Play Go in your terminal — local games and online play on OGS"
  homepage "https://github.com/tsraveling/gogo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gogo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gogo"]
    end
  end

  # No zap stanza required

end
